version: "3.8"

services:
  frontend:
    build: ./
    container_name: novohrad
    ports:
      - "90:90"
    restart: always
    networks:
      - bajerlukascz_network

networks:
  bajerlukascz_network:
    external: true